spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: wechat-work
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      GMT+8
  datasource:
    url: jdbc:mysql://124.70.156.27:31097/admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: s5tDuBAHdy
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1